# version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutor_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./ml:/ml
      - /var/run/docker.sock:/var/run/docker.sock # For sandbox docker calls
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@mysql/tutor_db
      - REDIS_URL=redis://redis:6379
      - MODEL_PATH=/ml/models/classifier.pkl
      - LE_PATH=/ml/models/le.pkl
      - TFIDF_PATH=/ml/models/tfidf.pkl
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
